d = open("rehber.dat","r", encoding="utf8")
gelen = d.read(8)
print(gelen)
gelen = d.read(5)
print(gelen)

d = open("rehber.dat","r", encoding="utf8")
gelen = d.read(8)
print(gelen)
gelen = d.read(5)
print(gelen)
gelen = d.readline()
print(gelen)
gelen = d.readline()
print(gelen)
gelen = d.readline()
print(gelen)
