def cizimmenu():
    print("╔═════════════════════╗")
    print("║     ÇİZİMLER        ║") 
    print("╠═════════════════════╣")
    print("║  1-Kare çiz         ║")
    print("║  2-Üçgen çiz        ║")
    print("║  3-Desen çizimi     ║")
    print("║  4-                 ║")
    print("║  5-                 ║")
    print("║  6-                 ║")
    print("║  7-                 ║")
    print("║  8-                 ║")
    print("║  9-                 ║")
    print("║ 10-                 ║")
    print("║ 11-                 ║")
    print("║                     ║")
    print("║    Seçimiz nedir?   ║")
    print("╚═════════════════════╝")

